
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.plaf.basic.BasicScrollBarUI;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dinus
 */
public class Customer_view_list extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewallItems
     */
    
    Connection con = null;
    Statement stmt = null;
    ResultSet rs = null;

    public Customer_view_list() {
            initComponents();
        
            /* remobe Border */
            this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
            BasicInternalFrameUI UIE = (BasicInternalFrameUI)this.getUI();
            UIE.setNorthPane(null);
        
            con = Database_connection_CLASS.connection();

            findUsers();
            
            scrollWindow.getViewport().setBackground(Color.WHITE);
            scrollWindow.setBorder(BorderFactory.createEmptyBorder());
            scrollWindow.getVerticalScrollBar().setUI(new BasicScrollBarUI() {
            @Override
            protected void configureScrollBarColors() {
                this.thumbColor = Color.gray;
            }
            });
        
    }
    
    public ArrayList<Customer_info_CLASS> CUSTOMERLIST(String ValToSearch)
    {
        ArrayList<Customer_info_CLASS> customerList = new ArrayList<Customer_info_CLASS>();
        

        try{
        
            stmt = con.createStatement();
            String searchQuery = "SELECT * FROM `customer` WHERE CONCAT(`customer_id`,`first_name`, `last_name`, `phone_number`, `address_line1`, `address_line2`, `zip`, `city`,`country`, `email`) LIKE '%"+ValToSearch+"%'";
            
            
            rs = stmt.executeQuery(searchQuery);
            
            Customer_info_CLASS displayCustomers;
            
            while(rs.next())
            {
                            
                displayCustomers = new Customer_info_CLASS(
                        
                        rs.getString("customer_id"),
                        rs.getString("first_name"),
                        rs.getString("last_name"),
                        rs.getString("phone_number"),
                        rs.getString("address_line1"),
                        rs.getString("address_line2"),
                        rs.getString("zip"),
                        rs.getString("country"),
                        rs.getString("city"),
                        rs.getString("email")

                                );
                customerList.add(displayCustomers);
            }
            
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        
        return customerList;
    }
    
    public void findUsers()
    {
        ArrayList<Customer_info_CLASS> users = CUSTOMERLIST(search.getText());
        DefaultTableModel model = new DefaultTableModel();

        model.setColumnIdentifiers(new Object[]{"id","Customer id","First Name","Last name","Contact number","Email","Address line 1","Address line 2","City","zip code","Country"});

        Object[] row = new Object[11];
        
        for(int i = 0; i < users.size(); i++)
        {
            int a = i + 1;
            row[0] =  a;
            row[1] = users.get(i).getCustomerID();
            row[2] = users.get(i).getFname();
            row[3] = users.get(i).getLname();
            row[4] = users.get(i).getPhone();
            row[5] = users.get(i).getEmail();
            row[6] = users.get(i).getAddress1();
            row[7] = users.get(i).getAddress2();
            row[8] = users.get(i).getCity();
            row[9] = users.get(i).getZip();
            row[10] = users.get(i).getCountry();


            model.addRow(row);
        }
       showTable.setModel(model);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scrollWindow = new javax.swing.JScrollPane();
        showTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showTable.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        showTable.setForeground(new java.awt.Color(51, 51, 51));
        showTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        showTable.setGridColor(new java.awt.Color(255, 255, 255));
        showTable.setRowHeight(30);
        showTable.setSelectionBackground(new java.awt.Color(0, 102, 102));
        showTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        showTable.getTableHeader().setResizingAllowed(false);
        showTable.getTableHeader().setReorderingAllowed(false);
        scrollWindow.setViewportView(showTable);

        jPanel1.add(scrollWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 1530, 480));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jPanel2.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 430, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Customer/listView-06.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -40, 670, 180));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 790, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        // TODO add your handling code here:
        try
        {
            findUsers();
        }
        catch(Exception e)
        {
            System.out.println(e);
            }
    }//GEN-LAST:event_searchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane scrollWindow;
    private javax.swing.JTextField search;
    private javax.swing.JTable showTable;
    // End of variables declaration//GEN-END:variables
}
