
import javax.swing.plaf.basic.BasicInternalFrameUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dinus
 */
public final class Customer_menu extends javax.swing.JInternalFrame {

    /**
     * Creates new form customer_menu
     */
    public static String USERNAME,userRole;
    
    public Customer_menu() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        String ID = USERNAME;
        Invoice_add_new.userid = ID;
        Invoice_update_menu.userid = ID;
        
        permissions();
        try
        {
 
            Customer_view_list view = new Customer_view_list ();
            WindowOpener.removeAll();
            WindowOpener.add(view).setVisible(true);

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }
    
    public void permissions(){
    
        try{
            if(null == userRole){
  
            }
            else switch (userRole) {
                case "admin":
                    break;
                case "master":
                    break;
                default:
                    remove_customer.setVisible(false);
                    break;
            }
        }
        catch(Exception e){
            System.out.println("Permission check Faild");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        WindowOpener = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        sell = new javax.swing.JButton();
        sell1 = new javax.swing.JButton();
        remove_customer = new javax.swing.JButton();
        sell3 = new javax.swing.JButton();
        sell4 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WindowOpener.setPreferredSize(new java.awt.Dimension(1518, 745));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );

        WindowOpener.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout WindowOpenerLayout = new javax.swing.GroupLayout(WindowOpener);
        WindowOpener.setLayout(WindowOpenerLayout);
        WindowOpenerLayout.setHorizontalGroup(
            WindowOpenerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        WindowOpenerLayout.setVerticalGroup(
            WindowOpenerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(WindowOpener, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 1610, 745));

        sell.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        sell.setForeground(new java.awt.Color(51, 51, 51));
        sell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons/icons8_view_32px_1.png"))); // NOI18N
        sell.setText("View all");
        sell.setContentAreaFilled(false);
        sell.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellActionPerformed(evt);
            }
        });
        jPanel1.add(sell, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, -1));

        sell1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        sell1.setForeground(new java.awt.Color(51, 51, 51));
        sell1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons/icons8_add_32px.png"))); // NOI18N
        sell1.setText("Add new customer");
        sell1.setContentAreaFilled(false);
        sell1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sell1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sell1ActionPerformed(evt);
            }
        });
        jPanel1.add(sell1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 220, -1));

        remove_customer.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        remove_customer.setForeground(new java.awt.Color(51, 51, 51));
        remove_customer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons/icons8_Remove_32px.png"))); // NOI18N
        remove_customer.setText("Remove customer");
        remove_customer.setContentAreaFilled(false);
        remove_customer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        remove_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_customerActionPerformed(evt);
            }
        });
        jPanel1.add(remove_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 220, -1));

        sell3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        sell3.setForeground(new java.awt.Color(51, 51, 51));
        sell3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons/icons8_update_32px.png"))); // NOI18N
        sell3.setText("Update customer");
        sell3.setContentAreaFilled(false);
        sell3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sell3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sell3ActionPerformed(evt);
            }
        });
        jPanel1.add(sell3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 220, -1));

        sell4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        sell4.setForeground(new java.awt.Color(51, 51, 51));
        sell4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons/icons8_view_details_32px_1.png"))); // NOI18N
        sell4.setText("View customer details");
        sell4.setContentAreaFilled(false);
        sell4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sell4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sell4ActionPerformed(evt);
            }
        });
        jPanel1.add(sell4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 270, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1610, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellActionPerformed
        // TODO add your handling code here:
        try
        {
            Customer_view_list view = new Customer_view_list ();
            WindowOpener.removeAll();
            WindowOpener.add(view).setVisible(true);

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
       
        
    }//GEN-LAST:event_sellActionPerformed

    private void sell1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sell1ActionPerformed
        // TODO add your handling code here:
        try
        {
            Customer_add_new view = new Customer_add_new ();
            WindowOpener.removeAll();
            WindowOpener.add(view).setVisible(true);

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_sell1ActionPerformed

    private void remove_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_customerActionPerformed
        // TODO add your handling code here:
        
        try
        {
            Cutomer_remove_menu view = new Cutomer_remove_menu ();
            WindowOpener.removeAll();
            WindowOpener.add(view).setVisible(true);

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_remove_customerActionPerformed

    private void sell3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sell3ActionPerformed
        // TODO add your handling code here:
        try
        {
            Cutomer_update_menu view = new Cutomer_update_menu ();
            WindowOpener.removeAll();
            WindowOpener.add(view).setVisible(true);

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_sell3ActionPerformed

    private void sell4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sell4ActionPerformed
        // TODO add your handling code here:
        try
        {
            Cutomer_view_menu view = new Cutomer_view_menu ();
            WindowOpener.removeAll();
            WindowOpener.add(view).setVisible(true);

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_sell4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane WindowOpener;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton remove_customer;
    private javax.swing.JButton sell;
    private javax.swing.JButton sell1;
    private javax.swing.JButton sell3;
    private javax.swing.JButton sell4;
    // End of variables declaration//GEN-END:variables
}
