
import javax.swing.plaf.basic.BasicInternalFrameUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dinus
 */
public class Dashboard_menu extends javax.swing.JInternalFrame {

    /**
     * Creates new form MainDashboard
     */
    public static String USERNAME;
    
    public Dashboard_menu() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        Dashboard_status view = new Dashboard_status ();
        WindowOpener.removeAll();
        WindowOpener.add(view).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        WindowOpener = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        Dashboard11 = new javax.swing.JButton();
        Dashboard12 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WindowOpener.setPreferredSize(new java.awt.Dimension(1518, 745));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1610, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );

        WindowOpener.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout WindowOpenerLayout = new javax.swing.GroupLayout(WindowOpener);
        WindowOpener.setLayout(WindowOpenerLayout);
        WindowOpenerLayout.setHorizontalGroup(
            WindowOpenerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        WindowOpenerLayout.setVerticalGroup(
            WindowOpenerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(WindowOpener, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 1610, 745));

        Dashboard11.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        Dashboard11.setForeground(new java.awt.Color(51, 51, 51));
        Dashboard11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/AdminPanel/icons8_time_machine_32px_2.png"))); // NOI18N
        Dashboard11.setText("recent activities");
        Dashboard11.setContentAreaFilled(false);
        Dashboard11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Dashboard11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dashboard11ActionPerformed(evt);
            }
        });
        jPanel1.add(Dashboard11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        Dashboard12.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        Dashboard12.setForeground(new java.awt.Color(51, 51, 51));
        Dashboard12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/AdminPanel/icons8_dashboard_32px_4.png"))); // NOI18N
        Dashboard12.setText("Dashboard");
        Dashboard12.setContentAreaFilled(false);
        Dashboard12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Dashboard12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dashboard12ActionPerformed(evt);
            }
        });
        jPanel1.add(Dashboard12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Dashboard11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dashboard11ActionPerformed
        // TODO add your handling code here:
        try
        {

            Dashboard_activities view = new Dashboard_activities ();
            WindowOpener.removeAll();
            WindowOpener.add(view).setVisible(true);

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_Dashboard11ActionPerformed

    private void Dashboard12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dashboard12ActionPerformed
        // TODO add your handling code here:
        try{
        
            Dashboard_status view = new Dashboard_status ();
            WindowOpener.removeAll();
            WindowOpener.add(view).setVisible(true);
        }
        catch(Exception e){
        
        }
    }//GEN-LAST:event_Dashboard12ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dashboard11;
    private javax.swing.JButton Dashboard12;
    private javax.swing.JDesktopPane WindowOpener;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
