
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dinus
 */
public final class Dashboard_activities extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewallItems
     */
    
    Connection con = null;
    Statement stmt = null;
    ResultSet rs = null;
    
    
    public Dashboard_activities() {
            initComponents();
        
            /* remobe Border */
            this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
            BasicInternalFrameUI UIE = (BasicInternalFrameUI)this.getUI();
            UIE.setNorthPane(null);
        
            con = Database_connection_CLASS.connection();

            findUsers();
            
            scrollWindow.getViewport().setBackground(Color.WHITE);
            scrollWindow.setBorder(BorderFactory.createEmptyBorder());
            
            
                    
//        cart_data.getTableHeader().setOpaque(false);
//        cart_data.getTableHeader().setBackground(Color.decode("#FCE7FC"));
//        cart_data.getTableHeader().setForeground(new Color(30, 232, 110 ));
        showTable.setRowHeight(50);
        
    }
    
    public ArrayList<Recent_activity_CLASS> AL (String ValToSearch)
    {
        ArrayList<Recent_activity_CLASS> activitylist = new ArrayList<Recent_activity_CLASS>();
        

        try{

            stmt = con.createStatement();
            String searchQuery = "SELECT * FROM `activity` WHERE CONCAT(`activity`) LIKE '%"+ValToSearch+"%'";
            
            
            rs = stmt.executeQuery(searchQuery);
            
            Recent_activity_CLASS displayActivity;
            
            while(rs.next())
            {
                            
                displayActivity = new Recent_activity_CLASS(
                        
                        rs.getString("activity")
                        
                                );
                activitylist.add(displayActivity);
            }
            
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
        
        return activitylist;
    }
    
    public void findUsers()
    {
        ArrayList<Recent_activity_CLASS> users = AL(search.getText());
        DefaultTableModel model = new DefaultTableModel();

        model.setColumnIdentifiers(new Object[]{" "});

        Object[] row = new Object[15];
        
        for(int i = 0; i < users.size(); i++)
        {
            row[0] = users.get(i).activityResent();
            
            model.addRow(row);
        }
       showTable.setModel(model);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        scrollWindow = new javax.swing.JScrollPane();
        showTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel2.setText("Activity");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 420, 40));

        scrollWindow.setBackground(new java.awt.Color(255, 255, 255));

        showTable.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        showTable.setForeground(new java.awt.Color(51, 51, 51));
        showTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12"
            }
        ));
        showTable.setGridColor(new java.awt.Color(255, 255, 255));
        showTable.setRowHeight(100);
        showTable.setSelectionBackground(new java.awt.Color(0, 102, 102));
        showTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        showTable.getTableHeader().setResizingAllowed(false);
        showTable.getTableHeader().setReorderingAllowed(false);
        scrollWindow.setViewportView(showTable);

        jPanel1.add(scrollWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 1530, 500));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jPanel2.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 430, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Products/list-06.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -30, 690, 160));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 790, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        // TODO add your handling code here:
        try
        {
            findUsers();
        }
        catch(Exception e)
        {
            System.out.println(e);
            }
    }//GEN-LAST:event_searchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane scrollWindow;
    private javax.swing.JTextField search;
    private javax.swing.JTable showTable;
    // End of variables declaration//GEN-END:variables
}
