
import javax.swing.plaf.basic.BasicInternalFrameUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dinus
 */
public class Invoice_menu extends javax.swing.JInternalFrame {

    /**
     * Creates new form MainDashboard
     */
    public static String USERNAME;
    
    public Invoice_menu() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        String ID = USERNAME;
        Invoice_add_new.userid = ID;
        Invoice_update_menu.userid = ID;
        try
        {
 
            Invoice_add_new view = new Invoice_add_new ();
            WindowOpener.removeAll();
            WindowOpener.add(view).setVisible(true);

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        WindowOpener = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        sell = new javax.swing.JButton();
        sell_history = new javax.swing.JButton();
        invoice_update = new javax.swing.JButton();
        sell_history2 = new javax.swing.JButton();
        reverse = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WindowOpener.setPreferredSize(new java.awt.Dimension(1518, 745));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1610, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );

        WindowOpener.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout WindowOpenerLayout = new javax.swing.GroupLayout(WindowOpener);
        WindowOpener.setLayout(WindowOpenerLayout);
        WindowOpenerLayout.setHorizontalGroup(
            WindowOpenerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        WindowOpenerLayout.setVerticalGroup(
            WindowOpenerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(WindowOpener, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 1610, 745));

        sell.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        sell.setForeground(new java.awt.Color(51, 51, 51));
        sell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons/icons8_add_receipt_32px.png"))); // NOI18N
        sell.setText("New Invoice");
        sell.setContentAreaFilled(false);
        sell.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellActionPerformed(evt);
            }
        });
        jPanel1.add(sell, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, -1));

        sell_history.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        sell_history.setForeground(new java.awt.Color(51, 51, 51));
        sell_history.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons/icons8_purchase_order_32px.png"))); // NOI18N
        sell_history.setText("View Invoice Details");
        sell_history.setContentAreaFilled(false);
        sell_history.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sell_history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sell_historyActionPerformed(evt);
            }
        });
        jPanel1.add(sell_history, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, -1, -1));

        invoice_update.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        invoice_update.setForeground(new java.awt.Color(51, 51, 51));
        invoice_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons/icons8_update_file_32px.png"))); // NOI18N
        invoice_update.setText("Update invoice ");
        invoice_update.setContentAreaFilled(false);
        invoice_update.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        invoice_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoice_updateActionPerformed(evt);
            }
        });
        jPanel1.add(invoice_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 210, -1));

        sell_history2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        sell_history2.setForeground(new java.awt.Color(51, 51, 51));
        sell_history2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons/icons8_order_history_32px.png"))); // NOI18N
        sell_history2.setText("Invoice History");
        sell_history2.setContentAreaFilled(false);
        sell_history2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sell_history2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sell_history2ActionPerformed(evt);
            }
        });
        jPanel1.add(sell_history2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 210, -1));

        reverse.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        reverse.setForeground(new java.awt.Color(51, 51, 51));
        reverse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons/icons8_delete_receipt_32px.png"))); // NOI18N
        reverse.setText("Invoice reverse");
        reverse.setContentAreaFilled(false);
        reverse.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        reverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reverseActionPerformed(evt);
            }
        });
        jPanel1.add(reverse, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1610, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellActionPerformed
        // TODO add your handling code here:
        try
        {
            Invoice_add_new view = new Invoice_add_new ();
            WindowOpener.removeAll();
            WindowOpener.add(view).setVisible(true);

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
       
        
    }//GEN-LAST:event_sellActionPerformed

    private void sell_historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sell_historyActionPerformed
        // TODO add your handling code here:
        
        try{
        
            Invoice_view_menu view = new Invoice_view_menu ();
            WindowOpener.removeAll();
            WindowOpener.add(view).setVisible(true);
            
        }
        catch(Exception e){
        
        }
        
    }//GEN-LAST:event_sell_historyActionPerformed

    private void invoice_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoice_updateActionPerformed
        // TODO add your handling code here:
        try{
        
            Invoice_update_menu view = new Invoice_update_menu ();
            WindowOpener.removeAll();
            WindowOpener.add(view).setVisible(true);
            
        }
        catch(Exception e){
        
        }
    }//GEN-LAST:event_invoice_updateActionPerformed

    private void sell_history2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sell_history2ActionPerformed
        // TODO add your handling code here:
        try{
        
            Invoice_history_menu view = new Invoice_history_menu ();
            WindowOpener.removeAll();
            WindowOpener.add(view).setVisible(true);
            
        }
        catch(Exception e){
        
        }
    }//GEN-LAST:event_sell_history2ActionPerformed

    private void reverseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reverseActionPerformed
        // TODO add your handling code here:
        try{
        
            Invoice_reverse_menu.userid = USERNAME;
            Invoice_reverse_menu view = new Invoice_reverse_menu ();
            WindowOpener.removeAll();
            WindowOpener.add(view).setVisible(true);
            
        }
        catch(Exception e){
        
            System.out.println("Cannot open reverse page");
        }
    }//GEN-LAST:event_reverseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane WindowOpener;
    private javax.swing.JButton invoice_update;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton reverse;
    private javax.swing.JButton sell;
    private javax.swing.JButton sell_history;
    private javax.swing.JButton sell_history2;
    // End of variables declaration//GEN-END:variables
}
