
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.plaf.basic.BasicScrollBarUI;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dinus
 */
public class Invoice_history extends javax.swing.JInternalFrame {

    /**
     * Creates new form invoice_history
     */
    Connection con = null;
    Statement stmt = null;
    ResultSet rs = null;
    
    public Invoice_history() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI UIE = (BasicInternalFrameUI)this.getUI();
        UIE.setNorthPane(null);
        
        con = Database_connection_CLASS.connection();
        ViewAll();
        
        invoiceHistory.getTableHeader().setOpaque(false);
        invoiceHistory.getTableHeader().setBackground(Color.WHITE);
        
        jScrollPane1.getViewport().setBackground(Color.WHITE);
        jScrollPane1.setBorder(BorderFactory.createEmptyBorder());
        
    }
    
    public ArrayList<Invoice_history_CLASS> invoiceHistory(String ValToSearch)
    {
        ArrayList<Invoice_history_CLASS> InvoiceHistory = new ArrayList<Invoice_history_CLASS>();
        

        try{
        
            stmt = con.createStatement();
            String searchQuery = "SELECT * FROM `invoice_details` WHERE CONCAT(`handle_user`, `invoice_number`, `date`,`invoiced_time` ,"
                    + "`due_date`, `fullname`,`invoice_total`,`payment_method`,`invoice_status`) LIKE '%"+ValToSearch+"%'";
            
            
            rs = stmt.executeQuery(searchQuery);
            
            Invoice_history_CLASS DishplayInvoiceHistory;
            
            while(rs.next())
            {
                            
                DishplayInvoiceHistory = new Invoice_history_CLASS(

                        rs.getString("invoice_number"),
                        rs.getString("fullname"),
                        rs.getString("date"),
                        rs.getString("invoiced_time"),
                        rs.getString("due_date"),
                        rs.getDouble("invoice_total"),
                        rs.getString("payment_method"),
                        rs.getString("handle_user"),
                        rs.getString("invoice_status")
         
                                );
                InvoiceHistory.add(DishplayInvoiceHistory);
            }
            
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        
        return InvoiceHistory;
    }
    
    public void ViewAll()
    {
        ArrayList<Invoice_history_CLASS> InvoiceHistory = invoiceHistory(searchButton.getText());
        DefaultTableModel model = new DefaultTableModel();
        
        model.setColumnIdentifiers(new Object[]{"No","Invoice Number","Client","Invoiced Date","Invoiced Time","Due Date","Invoice Total","Payment method","Handled User","Invoice Status"});

        Object[] row = new Object[10];
        
        for(int i = 0; i < InvoiceHistory.size(); i++)
        {

            int b = i; b++;
            row[0] = b;
            row[1] = InvoiceHistory.get(i).getIN();
            row[2] = InvoiceHistory.get(i).getClient();
            row[3] = InvoiceHistory.get(i).getInDate();
            row[4] = InvoiceHistory.get(i).getInTime();
            row[5] = InvoiceHistory.get(i).getInDue();
            row[6] = InvoiceHistory.get(i).getInTotal();
            row[7] = InvoiceHistory.get(i).getPayMethod();
            row[8] = InvoiceHistory.get(i).getHandledUser();
            row[9] = InvoiceHistory.get(i).getInvStatus();

            model.addRow(row);
        }
       invoiceHistory.setModel(model);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        searchButton = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        invoiceHistory = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        searchButton.setForeground(new java.awt.Color(0, 102, 102));
        searchButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchButtonKeyReleased(evt);
            }
        });
        jPanel1.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 400, 40));

        invoiceHistory.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        invoiceHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Invoice Number", "Client", "Invoiced Date", "Due Date", "Invoce Total", "Payment Method", "Handled user"
            }
        ));
        invoiceHistory.setGridColor(new java.awt.Color(255, 255, 255));
        invoiceHistory.setRowHeight(35);
        invoiceHistory.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jScrollPane1.setViewportView(invoiceHistory);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 1540, 510));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/History/history-06.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -12, 750, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1649, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchButtonKeyReleased
        // TODO add your handling code here:
        try{
            ViewAll();
        }
        catch(Exception e){
        
            
        }
    }//GEN-LAST:event_searchButtonKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable invoiceHistory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchButton;
    // End of variables declaration//GEN-END:variables
}
