
import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dinuss
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
        Connection con = null;
        Statement stmt = null;
        
    public Login() {
        
        try {
            UIManager.setLookAndFeel( new FlatIntelliJLaf() );
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
        initComponents();

        Errors();
        
        con = Database_connection_CLASS.connection();
        
        
    }
    public void Errors(){
    
        errorIcon.setVisible(false);
        errormassage.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        close1 = new javax.swing.JButton();
        forget = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        login = new accessories.Button();
        password = new accessories.PasswordField();
        errormassage = new javax.swing.JLabel();
        errorIcon = new javax.swing.JLabel();
        username = new accessories.TextField();
        jLabel1 = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        close1.setForeground(new java.awt.Color(0, 102, 102));
        close1.setText("Register Now");
        close1.setContentAreaFilled(false);
        close1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        close1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        close1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close1ActionPerformed(evt);
            }
        });
        jPanel2.add(close1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 160, 30));

        forget.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        forget.setForeground(new java.awt.Color(102, 102, 102));
        forget.setText("Forget Password? ");
        forget.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgetMouseClicked(evt);
            }
        });
        jPanel2.add(forget, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 150, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Don't you have Account yet?");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 230, 30));

        login.setBackground(new java.awt.Color(0, 102, 102));
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("LOGIN");
        login.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel2.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 350, 51));

        password.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        password.setLabelText("Password");
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 350, 81));

        errormassage.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        errormassage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        errormassage.setText("jLabel4");
        jPanel2.add(errormassage, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 328, 30));

        errorIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Errors/icons8_cancel_28px.png"))); // NOI18N
        jPanel2.add(errorIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 40, 30));

        username.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        username.setLabelText("Username");
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameKeyPressed(evt);
            }
        });
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 350, 93));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Login/login-01-01.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 360, 79));

        close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Public/icons8_delete_32px_1.png"))); // NOI18N
        close.setContentAreaFilled(false);
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Login/intro-01.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/forgetPassword/gg-01.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(215, 215, 215)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(714, 714, 714))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        try
        {
           System.exit(0);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_closeActionPerformed

    private void close1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close1ActionPerformed
        // TODO add your handling code here:
        try
        {
            this.setVisible(false);
            Master_login load1 = new Master_login ();
            load1.setVisible(true);

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_close1ActionPerformed

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
        // TODO add your handling code here:
        Errors();
    }//GEN-LAST:event_passwordKeyPressed

    private void usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyPressed
        // TODO add your handling code here:
        Errors();
    }//GEN-LAST:event_usernameKeyPressed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        try
        {
            if( username.getText().equals("")||password.getText().equals("")  )
            {

                errorIcon.setVisible(true);
                errormassage.setVisible(true);
                Color orange = new Color(255,102,0);
                errormassage.setForeground(orange);
                errormassage.setText("Username and password feil empty");
            }
            else
            {
                boolean loopcheck = false;

                stmt = con.createStatement();
                String query = "SELECT * FROM users ";

                String Username = username.getText();
                String Password = password.getText();

                ResultSet rs = stmt.executeQuery(query);

                while(rs.next())
                {
                    if (Username.equals(rs.getString(6)) && Password.equals(rs.getString(7)))
                    {
                        String LoggedTime = rs.getString(9);
                        if("1".equals(LoggedTime))
                        {
                            String ROLE = (rs.getString(8));
                            Dashboard.USERNAME = Username;
                            Dashboard.USERROLE = ROLE;
                            loopcheck = true;
                            setVisible(false);
                            Dashboard view2 = new Dashboard();
                            view2.setVisible(true);
                        }
                        else{
                        
                            SecuritysetupOne.username = Username;
                            loopcheck = true;
                            setVisible(false);
                            SecuritysetupOne view = new SecuritysetupOne();
                            view.setVisible(true);
                        }
                        
                        
//                        if("admin".equals(ROLE))
//                        {
//                            
//                        }
//
//                        else if("master".equals(ROLE))
//                        {
//                            //                            Home.passedusername = Username;
//                            loopcheck = true;
//                            setVisible(false);
//                            master_panel view = new master_panel();
//                            view.setVisible(true);
//
//                        }
//
//                        else
//                        {
//                            user_panel.USERNAME = Username;
//                            loopcheck = true;
//                            setVisible(false);
//                            user_panel view = new user_panel();
//                            view.setVisible(true);
//                        }
                    }
                }
                if(!loopcheck){

                    errorIcon.setVisible(true);
                    errormassage.setVisible(true);
                    Color red = new Color(255,0,0);
                    errormassage.setForeground(red);
                    errormassage.setText("Username and password not match");
                }
            }
        }
        catch (Exception e) {
            System.out.println(e);
            this.setVisible(false);
            Database_error_popup error = new Database_error_popup();
            error.setVisible(true);
            //            DatabaseError er = new DatabaseError ();
            //            er.setVisible(true);
        }
    }//GEN-LAST:event_loginActionPerformed

    private void forgetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetMouseClicked
        // TODO add your handling code here:
        try{

            this.setVisible(false);
            ForgetPasswordStep01 view = new ForgetPasswordStep01();
            view.setVisible(true);

        }
        catch(Exception e){

            System.out.println("Forget pw load error");
        }
    }//GEN-LAST:event_forgetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JButton close1;
    private javax.swing.JLabel errorIcon;
    private javax.swing.JLabel errormassage;
    private javax.swing.JLabel forget;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private accessories.Button login;
    private accessories.PasswordField password;
    private accessories.TextField username;
    // End of variables declaration//GEN-END:variables
}
