
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dinus
 */
public final class Profile_menu extends javax.swing.JInternalFrame {

    /**
     * Creates new form admin_profile
     */
    
    
    public static String passedusername,userRole;
    
    
    Connection con = null;
    Statement stmt = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    
    
    public Profile_menu() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI UIE = (BasicInternalFrameUI)this.getUI();
        UIE.setNorthPane(null);
        
        String id = passedusername;
        Profile_view.passedusername = id;
        Profile_settings.passedusername = id;
        Profile_security.passedusername = id;
        Profile_delete.passedusername = id;
       
        
        Profile_view view = new Profile_view ();
        window_opener.removeAll();
        window_opener.add(view).setVisible(true);
        
        permissions();
  
    }
    
    public void permissions(){
    
        try{
            if(null == userRole){
  
            }
            else switch (userRole) {
                case "admin":
                    break;
                case "master":
                    deleteAccount.setVisible(false);
                    jLabel4.setVisible(false);
                    break;
                default:
//                    deleteAccount.setVisible(false);
//                    jLabel4.setVisible(false);
                    break;
            }
        }
        catch(Exception e){
            System.out.println("Permission check Faild");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        your_profile = new javax.swing.JButton();
        account_settings = new javax.swing.JButton();
        password_security = new javax.swing.JButton();
        window_opener = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        deleteAccount = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        your_profile.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        your_profile.setForeground(new java.awt.Color(51, 51, 51));
        your_profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/AdminPanel/icons8_dashboard_32px_4.png"))); // NOI18N
        your_profile.setText("Your Profile");
        your_profile.setContentAreaFilled(false);
        your_profile.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        your_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                your_profileActionPerformed(evt);
            }
        });
        jPanel1.add(your_profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 270, -1));

        account_settings.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        account_settings.setForeground(new java.awt.Color(51, 51, 51));
        account_settings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/AdminPanel/icons8_dashboard_32px_4.png"))); // NOI18N
        account_settings.setText("Account settings");
        account_settings.setContentAreaFilled(false);
        account_settings.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        account_settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                account_settingsActionPerformed(evt);
            }
        });
        jPanel1.add(account_settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 280, -1));

        password_security.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        password_security.setForeground(new java.awt.Color(51, 51, 51));
        password_security.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/AdminPanel/icons8_dashboard_32px_4.png"))); // NOI18N
        password_security.setText("Password & security");
        password_security.setContentAreaFilled(false);
        password_security.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        password_security.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_securityActionPerformed(evt);
            }
        });
        jPanel1.add(password_security, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 280, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1240, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
        );

        window_opener.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout window_openerLayout = new javax.swing.GroupLayout(window_opener);
        window_opener.setLayout(window_openerLayout);
        window_openerLayout.setHorizontalGroup(
            window_openerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        window_openerLayout.setVerticalGroup(
            window_openerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(window_openerLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(window_opener, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 1240, 760));

        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Details abouut your presoal detls");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 280, 20));

        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Details abouut your presoal detls");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 280, 20));

        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Details abouut your presoal detls");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 280, 20));

        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Details abouut your presoal detls");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 280, 20));

        deleteAccount.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        deleteAccount.setForeground(new java.awt.Color(51, 51, 51));
        deleteAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/AdminPanel/icons8_dashboard_32px_4.png"))); // NOI18N
        deleteAccount.setText("Delete Account");
        deleteAccount.setContentAreaFilled(false);
        deleteAccount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        deleteAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAccountActionPerformed(evt);
            }
        });
        jPanel1.add(deleteAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 280, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void your_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_your_profileActionPerformed
        // TODO add your handling code here:
        try{
            Profile_view view = new Profile_view ();
            window_opener.removeAll();
            window_opener.add(view).setVisible(true);
        }
        catch(Exception e)
        {
        
        }
        
    }//GEN-LAST:event_your_profileActionPerformed

    private void account_settingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_account_settingsActionPerformed
        // TODO add your handling code here:
        
        try{
            Profile_settings view = new Profile_settings ();
            window_opener.removeAll();
            window_opener.add(view).setVisible(true);
        }
        catch(Exception e)
        {
        
        }
    }//GEN-LAST:event_account_settingsActionPerformed

    private void password_securityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_securityActionPerformed
        // TODO add your handling code here:
        try{
            Profile_security view = new Profile_security ();
            window_opener.removeAll();
            window_opener.add(view).setVisible(true);
        }
        catch(Exception e)
        {
        
        }
    }//GEN-LAST:event_password_securityActionPerformed

    private void deleteAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAccountActionPerformed
        // TODO add your handling code here:
        
        try{
            Profile_delete view = new Profile_delete ();
            window_opener.removeAll();
            window_opener.add(view).setVisible(true);
        }
        catch(Exception e)
        {
        
        }
    }//GEN-LAST:event_deleteAccountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton account_settings;
    private javax.swing.JButton deleteAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton password_security;
    private javax.swing.JDesktopPane window_opener;
    private javax.swing.JButton your_profile;
    // End of variables declaration//GEN-END:variables
}
