
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dinus
 */
public class Profile_security extends javax.swing.JInternalFrame {

    /**
     * Creates new form admin_profile_security
     */
    public static String passedusername;
    public static String dbpass;
    
    
    Connection con = null;
    Statement stmt = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    
    
    public Profile_security() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI UIE = (BasicInternalFrameUI)this.getUI();
        UIE.setNorthPane(null);
        
        pwError();
        scError();
        getPasswrod();
        
       
    }
    
    public void pwError(){
    
        pw_error_icon1.setVisible(false);
        pw_error_icon2.setVisible(false);
        error_msg.setVisible(false);
        
    }
    
    public void scError(){
    
        sc_error_icon1.setVisible(false);
        sc_error_icon2.setVisible(false);
        error_msg2.setVisible(false);
        
    }
    
    public void getPasswrod(){
    try{
        con = Database_connection_CLASS.connection();
        stmt = con.createStatement();
        String query = "SELECT * FROM users";
        ResultSet rs = stmt.executeQuery(query);
            
        while(rs.next())
            {
                if(passedusername.equals(rs.getString(2)))
                {
                    this.dbpass = rs.getString(7);
                }
            }
    }
    catch(Exception e){
    
    }
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lname2 = new javax.swing.JLabel();
        lname3 = new javax.swing.JLabel();
        lname4 = new javax.swing.JLabel();
        lname5 = new javax.swing.JLabel();
        new_password2 = new javax.swing.JPasswordField();
        new_password1 = new javax.swing.JPasswordField();
        current_password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lname6 = new javax.swing.JLabel();
        security_question_list = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lname7 = new javax.swing.JLabel();
        answer = new javax.swing.JTextField();
        lname8 = new javax.swing.JLabel();
        sc_password = new javax.swing.JPasswordField();
        lname9 = new javax.swing.JLabel();
        error_msg2 = new javax.swing.JLabel();
        error_msg = new javax.swing.JLabel();
        sc_error_icon1 = new javax.swing.JLabel();
        sc_error_icon2 = new javax.swing.JLabel();
        pw_error_icon1 = new javax.swing.JLabel();
        pw_error_icon2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        security_question_update = new accessories.Button();
        password_save = new accessories.Button();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lname2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        lname2.setForeground(new java.awt.Color(102, 102, 102));
        lname2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lname2.setText("Change Password");
        jPanel1.add(lname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 84, 470, -1));

        lname3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        lname3.setForeground(new java.awt.Color(51, 51, 51));
        lname3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lname3.setText("Current Password");
        jPanel1.add(lname3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 272, -1));

        lname4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        lname4.setForeground(new java.awt.Color(51, 51, 51));
        lname4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lname4.setText("New Password");
        jPanel1.add(lname4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 272, -1));

        lname5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        lname5.setForeground(new java.awt.Color(51, 51, 51));
        lname5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lname5.setText("Confirm New Password");
        jPanel1.add(lname5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 272, -1));

        new_password2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                new_password2KeyPressed(evt);
            }
        });
        jPanel1.add(new_password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 480, 40));

        new_password1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                new_password1KeyPressed(evt);
            }
        });
        jPanel1.add(new_password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 480, 40));

        current_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                current_passwordKeyPressed(evt);
            }
        });
        jPanel1.add(current_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 480, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jLabel1.setText("In order to protect your account, make sure your password:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 117, 534, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jLabel2.setText("• The Password must be at least 8 characters long");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 154, 390, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jLabel3.setText("• The Password must contain at least one special characters.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 460, -1));

        lname6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        lname6.setForeground(new java.awt.Color(102, 102, 102));
        lname6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lname6.setText("Update security questions for this account");
        jPanel1.add(lname6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 470, -1));

        security_question_list.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        security_question_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "In what city were you born?", "What is the name of your favorite pet?", "What is your mother's maiden name?", "What high school did you attend?", "What is the name of your first school?", "What was the make of your first car?", "What was your favorite food as a child?", "Where did you meet your spouse?" }));
        jPanel1.add(security_question_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 480, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jLabel4.setText("and make sure your answers are unforgettable.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 150, 540, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jLabel5.setText("Just in case you forget your password, choose security questions,");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 120, 530, -1));

        lname7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        lname7.setForeground(new java.awt.Color(51, 51, 51));
        lname7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lname7.setText("Current Password");
        jPanel1.add(lname7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 272, -1));

        answer.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        answer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                answerKeyPressed(evt);
            }
        });
        jPanel1.add(answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 480, 40));

        lname8.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        lname8.setForeground(new java.awt.Color(51, 51, 51));
        lname8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lname8.setText("Answer");
        jPanel1.add(lname8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 272, -1));

        sc_password.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        sc_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sc_passwordKeyPressed(evt);
            }
        });
        jPanel1.add(sc_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, 480, 40));

        lname9.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        lname9.setForeground(new java.awt.Color(51, 51, 51));
        lname9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lname9.setText("Select Security Question");
        jPanel1.add(lname9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 272, -1));

        error_msg2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        error_msg2.setText("jLabel4");
        jPanel1.add(error_msg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, 450, 60));

        error_msg.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        error_msg.setText("jLabel4");
        jPanel1.add(error_msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 371, 70));

        sc_error_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Errors/icons8_cancel_20px.png"))); // NOI18N
        jPanel1.add(sc_error_icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, -1, 70));

        sc_error_icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Errors/icons8_ok_20px.png"))); // NOI18N
        jPanel1.add(sc_error_icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, -1, 70));

        pw_error_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Errors/icons8_cancel_20px.png"))); // NOI18N
        jPanel1.add(pw_error_icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, 70));

        pw_error_icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Errors/icons8_ok_20px.png"))); // NOI18N
        jPanel1.add(pw_error_icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, 70));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jLabel6.setText("• The Password must contain at least one uppercase character.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 182, 470, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jLabel7.setText("• The Password must contain at least one lowercase character.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 460, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jLabel8.setText("• The Password must contain at least one digit ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 460, -1));

        security_question_update.setBackground(new java.awt.Color(255, 0, 51));
        security_question_update.setForeground(new java.awt.Color(255, 255, 255));
        security_question_update.setText("Save");
        security_question_update.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        security_question_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                security_question_updateActionPerformed(evt);
            }
        });
        jPanel1.add(security_question_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 520, 480, 40));

        password_save.setBackground(new java.awt.Color(255, 0, 51));
        password_save.setForeground(new java.awt.Color(255, 255, 255));
        password_save.setText("Save");
        password_save.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        password_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_saveActionPerformed(evt);
            }
        });
        jPanel1.add(password_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 480, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1311, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void current_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_current_passwordKeyPressed
        // TODO add your handling code here:
        try{
        
            pwError();
        }
        catch(Exception e){
        
        }
    }//GEN-LAST:event_current_passwordKeyPressed

    private void new_password1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_new_password1KeyPressed
        // TODO add your handling code here:
        try{
        
            pwError();
        }
        catch(Exception e){
        
        }
    }//GEN-LAST:event_new_password1KeyPressed

    private void new_password2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_new_password2KeyPressed
        // TODO add your handling code here:
        try{
        
            pwError();
        }
        catch(Exception e){
        
        }
    }//GEN-LAST:event_new_password2KeyPressed

    private void answerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_answerKeyPressed
        // TODO add your handling code here:
        try{
        
            scError();
        }
        catch(Exception e){
        
        }
    }//GEN-LAST:event_answerKeyPressed

    private void sc_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sc_passwordKeyPressed
        // TODO add your handling code here:
        try{
        
            scError();
        }
        catch(Exception e){
        
        }
        
    }//GEN-LAST:event_sc_passwordKeyPressed

    private void password_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_saveActionPerformed
        // TODO add your handling code here:
                try{
            String pw1 = current_password.getText();
            String pw2 = new_password1.getText();
            String pw3 = new_password2.getText();
            String id = passedusername;
            
            if( current_password.getText().equals("") || new_password1.getText().equals("") || new_password2.getText().equals("")){
               
                pwError();
                pw_error_icon1.setVisible(true);
                error_msg.setVisible(true);
                error_msg.setText("Feilds Empty");
            }
            else{
                
                if(pw1 == null ? dbpass == null : pw1.equals(dbpass)){
            
                    if(pw2 == null ? pw3 == null : pw2.equals(pw3)){

                        pwError();
                        pw_error_icon2.setVisible(true);
                        error_msg.setVisible(true);
                        error_msg.setText("password successfully changed");
                        String query2 ="UPDATE users SET  password = ?  WHERE user_id = ? ";
                        PreparedStatement preparedStmt = con.prepareStatement(query2);
                        preparedStmt.setString(1, pw3);
                        preparedStmt.setString(2, id);
                        preparedStmt.execute();
                         
                        
                    }
                    else{

                        pwError();
                        pw_error_icon1.setVisible(true);
                        error_msg.setVisible(true);
                        error_msg.setText("New password Doesnt match");
                    }
                }
                else{

                    pwError();
                    pw_error_icon1.setVisible(true);
                    error_msg.setVisible(true);
                    error_msg.setText("Old password doesnt macth");
                }

            }
            
        }
        catch(SQLException e){}
    }//GEN-LAST:event_password_saveActionPerformed

    private void security_question_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_security_question_updateActionPerformed
        // TODO add your handling code here:
        try{
            
            String pw = dbpass;
            String scl = security_question_list.getSelectedItem().toString();
            String Answer = answer.getText();
            String pw2 = sc_password.getText();
            String id = passedusername;
            
            if(answer.getText().equals("") || sc_password.getText().equals("")){
                
                error_msg2.setVisible(true);
                sc_error_icon1.setVisible(true);
                error_msg2.setText("Feilds are empty!");
                
            }
            else{
                
                if(pw == null ? pw2 == null : pw.equals(pw2)){
            
                    if(answer.getText().equals("")){

                        scError();
                        sc_error_icon1.setVisible(true);
                        error_msg2.setVisible(true);
                        error_msg2.setText("Enter an answer!");
                    }
                    else{

                        scError();
                        String query2 ="UPDATE users SET  security_question = ?, security_answer =? WHERE user_id = ? ";
                        PreparedStatement preparedStmt = con.prepareStatement(query2);
                        preparedStmt.setString(1, scl);
                        preparedStmt.setString(2, Answer);
                        preparedStmt.setString(3, id);
                        preparedStmt.execute();
                        sc_error_icon2.setVisible(true);
                        error_msg2.setVisible(true);  
                        error_msg2.setText("Security Question updated Sucessfully");
                        
                    }
                }
                else{
                    scError();
                    sc_error_icon1.setVisible(true);
                    error_msg2.setVisible(true);
                    error_msg2.setText("Invalid Password");
                }

            }

        }
        catch(SQLException e){}
    }//GEN-LAST:event_security_question_updateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answer;
    private javax.swing.JPasswordField current_password;
    private javax.swing.JLabel error_msg;
    private javax.swing.JLabel error_msg2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lname2;
    private javax.swing.JLabel lname3;
    private javax.swing.JLabel lname4;
    private javax.swing.JLabel lname5;
    private javax.swing.JLabel lname6;
    private javax.swing.JLabel lname7;
    private javax.swing.JLabel lname8;
    private javax.swing.JLabel lname9;
    private javax.swing.JPasswordField new_password1;
    private javax.swing.JPasswordField new_password2;
    private accessories.Button password_save;
    private javax.swing.JLabel pw_error_icon1;
    private javax.swing.JLabel pw_error_icon2;
    private javax.swing.JLabel sc_error_icon1;
    private javax.swing.JLabel sc_error_icon2;
    private javax.swing.JPasswordField sc_password;
    private javax.swing.JComboBox<String> security_question_list;
    private accessories.Button security_question_update;
    // End of variables declaration//GEN-END:variables
}
