
import java.awt.Color;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dinus
 */
public class Register_form extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public static String usernameSelected;
    public static String genaratedID;
    
    Connection con = null;
    Statement stmt = null;
    
    public Register_form() {
        initComponents();
        
        con = Database_connection_CLASS.connection();
        
        error.setVisible(false);
        ErrorIcon.setVisible(false);
  
        try{
            String currentUsername = usernameSelected;
            String currentID = genaratedID;
            username.setText(usernameSelected);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        close1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        container = new javax.swing.JLabel();
        Regiister = new keeptoo.KButton();
        error = new javax.swing.JLabel();
        changeuser = new keeptoo.KButton();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        username = new javax.swing.JLabel();
        password2 = new javax.swing.JPasswordField();
        ErrorIcon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        close1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        close1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Public/icons8_delete_32px_1.png"))); // NOI18N
        close1.setContentAreaFilled(false);
        close1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/MasterLogin/Registration/registerintro-01.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        container.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/MasterLogin/Registration/registerForm-01.png"))); // NOI18N
        container.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 878, -1));

        Regiister.setText("Register");
        Regiister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegiisterActionPerformed(evt);
            }
        });
        jPanel2.add(Regiister, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 620, -1, -1));

        error.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        error.setText("jLabel3");
        jPanel2.add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, 730, 40));

        changeuser.setText("Change Username");
        changeuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeuserActionPerformed(evt);
            }
        });
        jPanel2.add(changeuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 620, -1, -1));

        fname.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        fname.setForeground(new java.awt.Color(0, 102, 51));
        fname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fnameKeyReleased(evt);
            }
        });
        jPanel2.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 252, 290, 40));

        lname.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lname.setForeground(new java.awt.Color(0, 102, 51));
        lname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lnameKeyReleased(evt);
            }
        });
        jPanel2.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 252, 290, 40));

        email.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        email.setForeground(new java.awt.Color(0, 102, 51));
        email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailKeyReleased(evt);
            }
        });
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 280, 40));

        password.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        password.setForeground(new java.awt.Color(0, 102, 51));
        password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordKeyReleased(evt);
            }
        });
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 452, 300, 40));

        username.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        username.setForeground(new java.awt.Color(102, 102, 102));
        username.setText("jLabel2");
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 126, 340, 60));

        password2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        password2.setForeground(new java.awt.Color(0, 102, 51));
        password2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        password2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                password2KeyReleased(evt);
            }
        });
        jPanel2.add(password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 452, 300, 40));

        ErrorIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Errors/icons8_error_32px.png"))); // NOI18N
        jPanel2.add(ErrorIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 50, 60));

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(close1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(close1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void close1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close1ActionPerformed
        // TODO add your handling code here:
        try
        {
            System.exit(0);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_close1ActionPerformed

    private void RegiisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegiisterActionPerformed
        // TODO add your handling code here:
        try
        {
            stmt = con.createStatement();
            String pw1 = password.getText();
            String pw2 = password2.getText();

                if( fname.getText().equals("")|| lname.getText().equals("")|| fname.getText().equals("") || email.getText().equals("") || password.getText().equals("") )
                {
                    error.setVisible(true);
                    ErrorIcon.setVisible(true);
                    Color orange = new Color(255,102,0);
                    error.setForeground(orange);
                    error.setText("some feilds are misssing!");
                }


                else if(pw1.equals(pw2))
                {
                    String DBUSERID = genaratedID;
                    String DBFNAME = fname.getText();
                    String DBLNAME = lname.getText();
                    String DBUSERNAME = username.getText();
                    String DBEMAIL = email.getText();
                    String DBPASSWORD = password.getText();
                    
                    MessageDigest md = MessageDigest.getInstance("SHA-256");
                    md.update(DBPASSWORD.getBytes());
                    byte[] digest = md.digest();
  
                    for (byte b : digest) {
                        System.out.format("%02x", b);
                    }
                    
   
                    String query2 = "INSERT INTO users (user_id, fname, lname, username, email, password) VALUES (?, ?, ?, ?, ?, ?)";

                    PreparedStatement preparedStmt = con.prepareStatement(query2);

                    preparedStmt.setString(1, DBUSERID);
                    preparedStmt.setString(2, DBFNAME);
                    preparedStmt.setString(3, DBLNAME);
                    preparedStmt.setString(4, DBUSERNAME);
                    preparedStmt.setString(5, DBEMAIL);
                    preparedStmt.setString(6, DBPASSWORD);

                    preparedStmt.execute();
                                //            JOptionPane.showMessageDialog(null, "ADDED");
                    setVisible(false);
                    Succsess view = new Succsess ();
                    view.setVisible(true);

                    }
                else
                {
                    error.setVisible(true);
                    Color red = new Color(255,0,0);
                    error.setForeground(red);
                    error.setText("passwords does not match");

                }
            }
        
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_RegiisterActionPerformed

    private void fnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameKeyReleased
        // TODO add your handling code here:
        try
        {
            error.setVisible(false);
            ErrorIcon.setVisible(false);

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_fnameKeyReleased

    private void lnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnameKeyReleased
        // TODO add your handling code here:
        try
        {
            error.setVisible(false);
            ErrorIcon.setVisible(false);

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_lnameKeyReleased

    private void emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyReleased
        // TODO add your handling code here:
        try
        {
            error.setVisible(false);
            ErrorIcon.setVisible(false);

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_emailKeyReleased

    private void password2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password2KeyReleased
        // TODO add your handling code here:
        try
        {
            error.setVisible(false);
            ErrorIcon.setVisible(false);

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_password2KeyReleased

    private void passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyReleased
        // TODO add your handling code here:
        try
        {
            error.setVisible(false);
            ErrorIcon.setVisible(false);

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_passwordKeyReleased

    private void changeuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeuserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ErrorIcon;
    private keeptoo.KButton Regiister;
    private keeptoo.KButton changeuser;
    private javax.swing.JButton close1;
    private javax.swing.JLabel container;
    private javax.swing.JTextField email;
    private javax.swing.JLabel error;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lname;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField password2;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
