
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dinus
 */
public final class Settings extends javax.swing.JInternalFrame {

    /**
     * Creates new form settings
     */
    public static String USERNAME2,userRole;
    
    Connection con = null;
    Statement stmt = null;
    ResultSet rs = null;
    
    public Settings() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI UIE = (BasicInternalFrameUI)this.getUI();
        UIE.setNorthPane(null);
        
        permissions();
            
    }
    public void permissions(){
    
        try{
            if(null == userRole){
  
            }
            else switch (userRole) {
                case "admin":
                    factoryRest.setVisible(false);
                    jLabel6.setVisible(false);
                    break;
                case "master":
                    break;
                default:

                    break;
            }
        }
        catch(Exception e){
            System.out.println("Permission check Faild");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        your_profile = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userManagment = new javax.swing.JButton();
        resetInformations = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        factoryRest = new javax.swing.JButton();
        WindowOpener = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        your_profile.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        your_profile.setForeground(new java.awt.Color(51, 51, 51));
        your_profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/AdminPanel/icons8_dashboard_32px_4.png"))); // NOI18N
        your_profile.setText("Business Informations");
        your_profile.setContentAreaFilled(false);
        your_profile.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        your_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                your_profileActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Details abouut your presoal detls");

        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Details abouut your presoal detls");

        userManagment.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        userManagment.setForeground(new java.awt.Color(51, 51, 51));
        userManagment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/AdminPanel/icons8_dashboard_32px_4.png"))); // NOI18N
        userManagment.setText("Teams and Roles");
        userManagment.setContentAreaFilled(false);
        userManagment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userManagment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userManagmentActionPerformed(evt);
            }
        });

        resetInformations.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        resetInformations.setForeground(new java.awt.Color(51, 51, 51));
        resetInformations.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/AdminPanel/icons8_dashboard_32px_4.png"))); // NOI18N
        resetInformations.setText("Rest informations");
        resetInformations.setContentAreaFilled(false);
        resetInformations.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        resetInformations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetInformationsActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Details abouut your presoal detls");

        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Details abouut your presoal detls");

        factoryRest.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        factoryRest.setForeground(new java.awt.Color(51, 51, 51));
        factoryRest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/AdminPanel/icons8_dashboard_32px_4.png"))); // NOI18N
        factoryRest.setText("Factory reset Software");
        factoryRest.setContentAreaFilled(false);
        factoryRest.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        factoryRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factoryRestActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1290, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        WindowOpener.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout WindowOpenerLayout = new javax.swing.GroupLayout(WindowOpener);
        WindowOpener.setLayout(WindowOpenerLayout);
        WindowOpenerLayout.setHorizontalGroup(
            WindowOpenerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        WindowOpenerLayout.setVerticalGroup(
            WindowOpenerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resetInformations, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userManagment, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(your_profile)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(factoryRest, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WindowOpener))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WindowOpener, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(your_profile)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(userManagment))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(resetInformations))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(factoryRest))
                        .addGap(0, 424, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void your_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_your_profileActionPerformed
        // TODO add your handling code here:
        try{
            
        }
        catch(Exception e)
        {

        }

    }//GEN-LAST:event_your_profileActionPerformed

    private void userManagmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userManagmentActionPerformed
        // TODO add your handling code here:
        try
        {
            User_menu view = new User_menu ();
            WindowOpener.removeAll();
            WindowOpener.add(view).setVisible(true);

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_userManagmentActionPerformed

    private void resetInformationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetInformationsActionPerformed
        // TODO add your handling code here:
        try
        {
            Reset_information view = new Reset_information ();
            WindowOpener.removeAll();
            WindowOpener.add(view).setVisible(true);

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_resetInformationsActionPerformed

    private void factoryRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factoryRestActionPerformed
        // TODO add your handling code here:
        
        try
        {
            Factory_reset view = new Factory_reset ();
            WindowOpener.removeAll();
            WindowOpener.add(view).setVisible(true);

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_factoryRestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane WindowOpener;
    private javax.swing.JButton factoryRest;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton resetInformations;
    private javax.swing.JButton userManagment;
    private javax.swing.JButton your_profile;
    // End of variables declaration//GEN-END:variables
}
