
import javax.swing.plaf.basic.BasicInternalFrameUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dinus
 */
public final class Supplier_menu extends javax.swing.JInternalFrame {

    /**
     * Creates new form supplier_menu
     */
    public static String USERNAME,userRole;
    
    public Supplier_menu() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        Supplier_update_menu.userid = USERNAME;
        permissions();
        try
        {
 
            Supplier_list view = new Supplier_list ();
            WindowOpener.removeAll();
            WindowOpener.add(view).setVisible(true);

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }
    
    public void permissions(){
    
        try{
            if(null == userRole){
  
            }
            else switch (userRole) {
                case "admin":
                    break;
                case "master":
                    break;
                default:
                    removeSupplier.setVisible(false);
                    break;
            }
        }
        catch(Exception e){
            System.out.println("Permission check Faild");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        WindowOpener = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        viewFull = new javax.swing.JButton();
        viewAll = new javax.swing.JButton();
        Additems = new javax.swing.JButton();
        Dashboard12 = new javax.swing.JButton();
        removeSupplier = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WindowOpener.setPreferredSize(new java.awt.Dimension(1518, 745));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1610, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );

        WindowOpener.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout WindowOpenerLayout = new javax.swing.GroupLayout(WindowOpener);
        WindowOpener.setLayout(WindowOpenerLayout);
        WindowOpenerLayout.setHorizontalGroup(
            WindowOpenerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        WindowOpenerLayout.setVerticalGroup(
            WindowOpenerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(WindowOpener, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 1610, 740));

        viewFull.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        viewFull.setForeground(new java.awt.Color(51, 51, 51));
        viewFull.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons/icons8_view_details_32px_1.png"))); // NOI18N
        viewFull.setText("View supplier details");
        viewFull.setContentAreaFilled(false);
        viewFull.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        viewFull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFullActionPerformed(evt);
            }
        });
        jPanel1.add(viewFull, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, -1, -1));

        viewAll.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        viewAll.setForeground(new java.awt.Color(51, 51, 51));
        viewAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons/icons8_view_32px_1.png"))); // NOI18N
        viewAll.setText("View all");
        viewAll.setContentAreaFilled(false);
        viewAll.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        viewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllActionPerformed(evt);
            }
        });
        jPanel1.add(viewAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, -1));

        Additems.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        Additems.setForeground(new java.awt.Color(51, 51, 51));
        Additems.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons/icons8_add_32px.png"))); // NOI18N
        Additems.setText("Add new supplier");
        Additems.setContentAreaFilled(false);
        Additems.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Additems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdditemsActionPerformed(evt);
            }
        });
        jPanel1.add(Additems, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        Dashboard12.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        Dashboard12.setForeground(new java.awt.Color(51, 51, 51));
        Dashboard12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons/icons8_update_32px.png"))); // NOI18N
        Dashboard12.setText("Update supplier details ");
        Dashboard12.setContentAreaFilled(false);
        Dashboard12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Dashboard12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dashboard12ActionPerformed(evt);
            }
        });
        jPanel1.add(Dashboard12, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, -1, -1));

        removeSupplier.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        removeSupplier.setForeground(new java.awt.Color(51, 51, 51));
        removeSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons/icons8_Remove_32px.png"))); // NOI18N
        removeSupplier.setText("Remove supplier");
        removeSupplier.setContentAreaFilled(false);
        removeSupplier.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        removeSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSupplierActionPerformed(evt);
            }
        });
        jPanel1.add(removeSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1610, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllActionPerformed
        // TODO add your handling code here:
        try
        {

            Supplier_list view = new Supplier_list ();
            WindowOpener.removeAll();
            WindowOpener.add(view).setVisible(true);

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_viewAllActionPerformed

    private void AdditemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdditemsActionPerformed
        // TODO add your handling code here:
        try
        {
            //            String Uid = passedusername;
            //            AdminDashboard.userid = Uid;
                        Supplier_add_new view = new Supplier_add_new ();
                        WindowOpener.removeAll();
                        WindowOpener.add(view).setVisible(true);

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_AdditemsActionPerformed

    private void viewFullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFullActionPerformed
        // TODO add your handling code here:
        try
        {
            Supplier_view_menu view = new Supplier_view_menu ();
            WindowOpener.removeAll();
            WindowOpener.add(view).setVisible(true);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_viewFullActionPerformed

    private void Dashboard12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dashboard12ActionPerformed
        // TODO add your handling code here:
        try
        {
            Supplier_update_menu view = new Supplier_update_menu ();
            WindowOpener.removeAll();
            WindowOpener.add(view).setVisible(true);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_Dashboard12ActionPerformed

    private void removeSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSupplierActionPerformed
        // TODO add your handling code here:
        
        try
        {
            Supplier_remove_menu view = new Supplier_remove_menu ();
            WindowOpener.removeAll();
            WindowOpener.add(view).setVisible(true);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_removeSupplierActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Additems;
    private javax.swing.JButton Dashboard12;
    private javax.swing.JDesktopPane WindowOpener;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton removeSupplier;
    private javax.swing.JButton viewAll;
    private javax.swing.JButton viewFull;
    // End of variables declaration//GEN-END:variables
}
