
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dinus
 */
public class Username_check extends javax.swing.JFrame {

    /**
     * Creates new form UsernameCheck
     */
    
    Connection con = null;
    Statement stmt = null;
    
    public Username_check() {
        initComponents();
        
        con = Database_connection_CLASS.connection();
        
        right.setVisible(false);
        wrong.setVisible(false);
        emp1.setVisible(false);
        errormassage.setVisible(false);
        next.setVisible(false);
    }
    
    public void Queary(){
    
        try
        {
            stmt = con.createStatement();
            String userid = username.getText();

            if( username.getText().equals("") )
            {
                next.setVisible(false);
                emp1.setVisible(true);
                errormassage.setVisible(true);
                Color orange = new Color(255,102,0);
                errormassage.setForeground(orange);
                errormassage.setText("Null input feild");
            }
            else
            {
                boolean loopcheck = false;
                stmt = con.createStatement();
                String query = "SELECT * FROM users ";
                String Username = username.getText();
                ResultSet rs = stmt.executeQuery(query);
                while(rs.next())
                {
                    if (Username.equals(rs.getString(6)))
                    {

//                          username Validation
                        next.setVisible(false);
                            loopcheck = true;
                            wrong.setVisible(true);
                            errormassage.setVisible(true);
                            Color red = new Color(255,0,0);
                            errormassage.setForeground(red);
                            errormassage.setText("username not vailable");  
                    }
                }
                if(!loopcheck){
                    
                    Register_form.usernameSelected = Username;
                    wrong.setVisible(false);
                    right.setVisible(true);
                    errormassage.setVisible(true);
                    Color red = new Color(0,153,51);
                    errormassage.setForeground(red);
                    errormassage.setText("Username available");
                    String GENID = null;
                    stmt = con.createStatement();
                    rs = stmt.executeQuery("SELECT MAX(user_id) FROM users");
                    rs.next();
                    rs.getString("MAX(user_id)");
                    if (rs.getString("MAX(user_id)") == null) {
                        
                            GENID = "ID00000001";
                            Register_form.genaratedID = GENID;       
                    }
                    else {
                        
                        long id = Long.parseLong(rs.getString("MAX(user_id)").substring(2, rs.getString("MAX(user_id)").length()));
                        id++;
                        GENID = ("ID" + String.format("%08d", id)); 
                        Register_form.genaratedID = GENID;
                    }
                }   
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        close1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        usernamebar = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        next = new keeptoo.KButton();
        emp1 = new javax.swing.JLabel();
        wrong = new javax.swing.JLabel();
        right = new javax.swing.JLabel();
        errormassage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        close1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Public/icons8_delete_32px_1.png"))); // NOI18N
        close1.setContentAreaFilled(false);
        close1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close1ActionPerformed(evt);
            }
        });
        jPanel1.add(close1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1538, 34, 27, 26));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernamebar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/MasterLogin/username check/checkbar-01.png"))); // NOI18N
        jPanel2.add(usernamebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 63));

        close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Public/icons8_search_32px_2.png"))); // NOI18N
        close.setContentAreaFilled(false);
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel2.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, 40));

        username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usernameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameKeyTyped(evt);
            }
        });
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 390, 30));

        next.setText("NEXT");
        next.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel2.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        emp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Errors/icons8_box_important_28px.png"))); // NOI18N
        jPanel2.add(emp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 40, 60));

        wrong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Errors/icons8_cancel_28px.png"))); // NOI18N
        jPanel2.add(wrong, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, 60));

        right.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Errors/icons8_ok_28px.png"))); // NOI18N
        jPanel2.add(right, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 292, -1, -1));

        errormassage.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        errormassage.setForeground(new java.awt.Color(0, 153, 51));
        errormassage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        errormassage.setText("jLabel4");
        jPanel1.add(errormassage, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 330, 480, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        try
        {
            System.exit(0);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_closeActionPerformed

    private void usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyTyped
        // TODO add your handling code here:
        try
        {
            next.setVisible(true);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
            
    }//GEN-LAST:event_usernameKeyTyped

    private void usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyPressed
        // TODO add your handling code here:
        try
        {
            errormassage.setVisible(false);
            right.setVisible(false);
            wrong.setVisible(false);
            emp1.setVisible(false);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_usernameKeyPressed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        try
        {   
            this.setVisible(false);
            Register_form reg = new Register_form();
            reg.setVisible(true);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_nextActionPerformed

    private void usernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyReleased
        // TODO add your handling code here:
        try
        {   
            Queary();
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_usernameKeyReleased

    private void close1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close1ActionPerformed
        // TODO add your handling code here:
        try
        {
            System.exit(0);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_close1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Username_check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Username_check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Username_check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Username_check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Username_check().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JButton close1;
    private javax.swing.JLabel emp1;
    private javax.swing.JLabel errormassage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private keeptoo.KButton next;
    private javax.swing.JLabel right;
    private javax.swing.JTextField username;
    private javax.swing.JLabel usernamebar;
    private javax.swing.JLabel wrong;
    // End of variables declaration//GEN-END:variables
}
