
import javax.swing.plaf.basic.BasicInternalFrameUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dinus
 */
public class User_menu extends javax.swing.JInternalFrame {

    /**
     * Creates new form user_menu
     */
    public static String USERNAME;
    
    public User_menu() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        try
        {
 
            User_list view = new User_list ();
            WindowOpener.removeAll();
            WindowOpener.add(view).setVisible(true);

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        WindowOpener = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        viewAll = new javax.swing.JButton();
        Additems = new javax.swing.JButton();
        Additems2 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WindowOpener.setPreferredSize(new java.awt.Dimension(1518, 745));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1610, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );

        WindowOpener.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout WindowOpenerLayout = new javax.swing.GroupLayout(WindowOpener);
        WindowOpener.setLayout(WindowOpenerLayout);
        WindowOpenerLayout.setHorizontalGroup(
            WindowOpenerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        WindowOpenerLayout.setVerticalGroup(
            WindowOpenerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(WindowOpener, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 1610, 745));

        viewAll.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        viewAll.setForeground(new java.awt.Color(51, 51, 51));
        viewAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/AdminPanel/icons8_dashboard_32px_4.png"))); // NOI18N
        viewAll.setText("View all");
        viewAll.setContentAreaFilled(false);
        viewAll.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        viewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllActionPerformed(evt);
            }
        });
        jPanel1.add(viewAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, -1));

        Additems.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        Additems.setForeground(new java.awt.Color(51, 51, 51));
        Additems.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/AdminPanel/icons8_time_machine_32px_2.png"))); // NOI18N
        Additems.setText("Add new user");
        Additems.setContentAreaFilled(false);
        Additems.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Additems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdditemsActionPerformed(evt);
            }
        });
        jPanel1.add(Additems, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, -1));

        Additems2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        Additems2.setForeground(new java.awt.Color(51, 51, 51));
        Additems2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/AdminPanel/icons8_time_machine_32px_2.png"))); // NOI18N
        Additems2.setText("Manage user");
        Additems2.setContentAreaFilled(false);
        Additems2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Additems2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Additems2ActionPerformed(evt);
            }
        });
        jPanel1.add(Additems2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1610, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllActionPerformed
        // TODO add your handling code here:
        try
        {

            User_list view = new User_list ();
            WindowOpener.removeAll();
            WindowOpener.add(view).setVisible(true);

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_viewAllActionPerformed

    private void AdditemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdditemsActionPerformed
        // TODO add your handling code here:
        try
        {

                        User_add_new view = new User_add_new ();
                        WindowOpener.removeAll();
                        WindowOpener.add(view).setVisible(true);

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_AdditemsActionPerformed

    private void Additems2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Additems2ActionPerformed
        // TODO add your handling code here:
        try
        {

            User_manage_menu view = new User_manage_menu ();
            WindowOpener.removeAll();
            WindowOpener.add(view).setVisible(true);

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_Additems2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Additems;
    private javax.swing.JButton Additems2;
    private javax.swing.JDesktopPane WindowOpener;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton viewAll;
    // End of variables declaration//GEN-END:variables
}
